= Implementing BGP Load Balancing infrastructure with MetalLB for OpenShift Virtualization
:page-title: Implementing BGP Load Balancing infrastructure with MetalLB for OpenShift Virtualization
:sectnums!:
:sectlinks:
:doctype: book

[#bgp-lb-addedum]
== 4. Developer Resources

### 4.1. Addendum: versions, notes and configurations related to this Proof-of-Concept

[cols="2,3,1,5a"]
|===
| *Infrastructure Elements* | *Components* | *Version* | *Notes and Configuration Details*

.4+| *Primary OpenShift Virtualization*
| Red Hat OpenShift
| 4.19
| 

Enable Global ipForwarding and routingViaHost:
----
oc patch network.operator cluster --type=merge -p '{"spec":{"defaultNetwork":{"ovnKubernetesConfig":{"gatewayConfig":{"ipForwarding": "Global"}}}}}'
oc patch network.operator cluster --type=merge -p '{"spec":{"defaultNetwork":{"ovnKubernetesConfig":{"gatewayConfig":{"routingViaHost": true}}}}}'
----

labels assigned to the worker nodes for MetalLB:
----
oc label node hub-worker01.ocp4-hub.test.com app=metallb-worker
oc label node hub-worker02.ocp4-hub.test.com app=metallb-worker
----

label assigned to the worker nodes for NMState:
----
oc label node hub-worker01.ocp4-hub.test.com node-role.kubernetes.io/BGPspeaker=""
oc label node hub-worker02.ocp4-hub.test.com node-role.kubernetes.io/BGPspeaker=""
----

NOTE: External IP assignment for noobaa-mgmt/s3 is disabled per link:https://access.redhat.com/solutions/6995857[RH Solution 6995857].

| LocalStorage / OpenShift Data Foundation / OpenShift Virtualization Operators
| 4.19
| Standard operator stack for storage and virtualization.

| OADP Operator
| 1.5.2
| xref:ROOT:attachment$configurations/ocp_virt-ocp_hub_oadp.zip[OADP Hub configuration]

| NMState / MetalLB Operators
| 4.19
| xref:ROOT:attachment$configurations/ocp_virt-ocp_hub_nmstate.zip[NMState configuration] +
xref:ROOT:attachment$configurations/ocp_virt-ocp_hub_metallb.zip[MetalLB configuration]

.4+| *DR OpenShift Virtualization*
| Red Hat OpenShift
| 4.19
| 

Enable Global ipForwarding and routingViaHost:
----
oc patch network.operator cluster --type=merge -p '{"spec":{"defaultNetwork":{"ovnKubernetesConfig":{"gatewayConfig":{"ipForwarding": "Global"}}}}}'
oc patch network.operator cluster --type=merge -p '{"spec":{"defaultNetwork":{"ovnKubernetesConfig":{"gatewayConfig":{"routingViaHost": true}}}}}'
----

labels assigned to the worker nodes for MetalLB:
----
oc label node dr-worker01.ocp4-dr.test.com app=metallb-worker
oc label node dr-worker02.ocp4-dr.test.com app=metallb-worker
----

label assigned to the worker nodes for NMState:
----
oc label node dr-worker01.ocp4-dr.test.com node-role.kubernetes.io/BGPspeaker=""
oc label node dr-worker02.ocp4-dr.test.com node-role.kubernetes.io/BGPspeaker=""
----

NOTE: External IP assignment for noobaa-mgmt/s3 is disabled per link:https://access.redhat.com/solutions/6995857[RH Solution 6995857].

| LocalStorage / OpenShift Data Foundation / OpenShift Virtualization Operators
| 4.19
| Standard operator stack for DR site.

| OADP Operator
| 1.5.2
| xref:ROOT:attachment$configurations/ocp_virt-ocp_dr_oadp.zip[OADP DR configuration]

| NMState / MetalLB Operators
| 4.19
| xref:ROOT:attachment$configurations/ocp_virt-ocp_dr_nmstate.zip[NMState DR configuration] +
xref:ROOT:attachment$configurations/ocp_virt-ocp_dr_metallb.zip[MetalLB DR configuration]

.3+| *Router & Network Services*
| FRRouting (Hub/Access/DR)
| 10.4.1
| 
* xref:ROOT:attachment$configurations/rtr-frr01-hub.zip[Hub Router configuration]
* xref:ROOT:attachment$configurations/rtr-frr02-access.zip[Access Router configuration]
* xref:ROOT:attachment$configurations/rtr-frr03-dr.zip[DR Router configuration]

| dhcp-server
| 4.4.2
| RHEL 9 package (4.4.2-19.b1.el9.x86_64)

| firewalld
| 1.3.4
| RHEL 9 package (1.3.4-9.el9_5.noarch)

| *External S3 Storage*
| Red Hat Ceph Storage (Single Node)
| N/A
| Ceph utilized as S3 backend for OADP. +
Reference: link:https://www.redhat.com/en/blog/ceph-cluster-single-machine[Creating a Ceph cluster on a single machine].
|===
