
= Implementing BGP Load Balancing infrastructure with MetalLB for OpenShift Virtualization

:page-layout: home
:sectnums:
:sectlinks:
:doctype: book


* The objective of this *Proof of Concept* is to transition traffic routing intelligence from physical hardware to the software-defined network control plane. 
* By designating ExternalIPAddresses of the loadBalancer services (MetalLB Layer3) as BGP endpoints, the system can automatically re-route traffic in the event of site failures or service disruptions, thereby establishing a cost-effective and scalable framework for modern disaster recovery.

*Contributors:* Riccardo Bruzzone (Senior Technical Account Manager) and Daniele Nessilli (Technical Account Manager)

++++
<br>
++++

== Getting Started

* Welcome to the Red Hat Solution Pattern. 
* Please use the navigation menu on the left or click "Next" below to proceed through the solution (Implementing BGP Load Balancing Infrastructure with MetalLB for OpenShift Virtualization*.

// [#bgp-lb]
//
// include::01-bgp-lb.adoc[]
//
// ++++
// <br>
// ++++
// [#bgp-adm-metallb-bgp]
// 
// #include::02-metallb-and-bgp.adoc[]
// 
// ++++
// <br>
// ++++
// [#bgp-lb-poc]
// 
// include::03-bgp-lb-poc.adoc[]
// 
// ++++
// <br>
// ++++
// [#bgp-lb-addedum]
// 
// include::04-bgp-lb-addendum.adoc[]
